- name: Enable/Start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user opc to docker group
  user:
    name: opc
    groups: docker
    append: yes

- name: Docker compose directory
  file:
    path: "{{ user_config.home_dir }}/.docker/cli-plugins/"
    state: directory

- name: Download Docker Compose 2
  get_url:
    url: "{{ docker_config.docker_compose2_arm64 }}"
    dest: "{{ user_config.home_dir }}/.docker/cli-plugins/docker-compose"
    mode: 0555

# - name: Start the Docker containers
#   shell: 
#     cmd: "docker compose up -d"
#     chdir: "{{ user_config.home_dir }}/wordpress"