- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Enable Oracle Epel Repo
  replace:
    path: /etc/yum.repos.d/oracle-epel-ol8.repo
    regexp: enabled=0
    replace: enabled=1

- name: Install Necessary Packages
  dnf:
    name:
      - vim
      - htop
      - tree
      - dnf-utils
      - zip
      - unzip

- name: Add Docker Repo
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker Engine
  dnf:
    name:
      - docker-ce