version: "3.9"
    
services:
  db:
    image: mysql:latest # arm64v8/mariadb 
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: <mysql_root_pass>
      MYSQL_DATABASE: <mysql_database>
      MYSQL_USER: <mysql_user>
      MYSQL_PASSWORD: <mysql_password>
    networks:
      proxynet:
  phpmyadmin:
    depends_on:
      - db
    image: arm64v8/phpmyadmin 
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: <mysql_root_pass>
    networks:
      proxynet:
  wordpress:
    image: arm64v8/wordpress 
    container_name: wordpress
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: <mysql_user>
      WORDPRESS_DB_PASSWORD: <mysql_password>
      WORDPRESS_DB_NAME: <mysql_database>
      WORDPRESS_DEBUG: 'true'
    volumes:
      - ./html:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    networks:
      proxynet:
  reverse:
    image: arm64v8/nginx 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      proxynet:
volumes:
  db_data: {}
  wordpress: {}
networks:
  proxynet: